# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BinaryMask.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BinaryMask.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x42inaryMask.proto\";\n\nBinaryMask\x12\x0e\n\x06points\x18\x01 \x03(\r\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\";\n\nDepthFrame\x12\x0e\n\x06points\x18\x01 \x03(\r\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"O\n\x0bMaskedFrame\x12\x1f\n\nbinaryMask\x18\x01 \x01(\x0b\x32\x0b.BinaryMask\x12\x1f\n\ndepthFrame\x18\x02 \x01(\x0b\x32\x0b.DepthFrame\"2\n\x12\x42inaryMaskSequence\x12\x1c\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x0c.MaskedFrameb\x06proto3')
)




_BINARYMASK = _descriptor.Descriptor(
  name='BinaryMask',
  full_name='BinaryMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='BinaryMask.points', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='BinaryMask.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='BinaryMask.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=79,
)


_DEPTHFRAME = _descriptor.Descriptor(
  name='DepthFrame',
  full_name='DepthFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='DepthFrame.points', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='DepthFrame.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='DepthFrame.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=140,
)


_MASKEDFRAME = _descriptor.Descriptor(
  name='MaskedFrame',
  full_name='MaskedFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='binaryMask', full_name='MaskedFrame.binaryMask', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depthFrame', full_name='MaskedFrame.depthFrame', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=221,
)


_BINARYMASKSEQUENCE = _descriptor.Descriptor(
  name='BinaryMaskSequence',
  full_name='BinaryMaskSequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='BinaryMaskSequence.frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=273,
)

_MASKEDFRAME.fields_by_name['binaryMask'].message_type = _BINARYMASK
_MASKEDFRAME.fields_by_name['depthFrame'].message_type = _DEPTHFRAME
_BINARYMASKSEQUENCE.fields_by_name['frames'].message_type = _MASKEDFRAME
DESCRIPTOR.message_types_by_name['BinaryMask'] = _BINARYMASK
DESCRIPTOR.message_types_by_name['DepthFrame'] = _DEPTHFRAME
DESCRIPTOR.message_types_by_name['MaskedFrame'] = _MASKEDFRAME
DESCRIPTOR.message_types_by_name['BinaryMaskSequence'] = _BINARYMASKSEQUENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BinaryMask = _reflection.GeneratedProtocolMessageType('BinaryMask', (_message.Message,), dict(
  DESCRIPTOR = _BINARYMASK,
  __module__ = 'BinaryMask_pb2'
  # @@protoc_insertion_point(class_scope:BinaryMask)
  ))
_sym_db.RegisterMessage(BinaryMask)

DepthFrame = _reflection.GeneratedProtocolMessageType('DepthFrame', (_message.Message,), dict(
  DESCRIPTOR = _DEPTHFRAME,
  __module__ = 'BinaryMask_pb2'
  # @@protoc_insertion_point(class_scope:DepthFrame)
  ))
_sym_db.RegisterMessage(DepthFrame)

MaskedFrame = _reflection.GeneratedProtocolMessageType('MaskedFrame', (_message.Message,), dict(
  DESCRIPTOR = _MASKEDFRAME,
  __module__ = 'BinaryMask_pb2'
  # @@protoc_insertion_point(class_scope:MaskedFrame)
  ))
_sym_db.RegisterMessage(MaskedFrame)

BinaryMaskSequence = _reflection.GeneratedProtocolMessageType('BinaryMaskSequence', (_message.Message,), dict(
  DESCRIPTOR = _BINARYMASKSEQUENCE,
  __module__ = 'BinaryMask_pb2'
  # @@protoc_insertion_point(class_scope:BinaryMaskSequence)
  ))
_sym_db.RegisterMessage(BinaryMaskSequence)


# @@protoc_insertion_point(module_scope)
