import math

DATA_SHAPE = (424, 512)
DATA_DOWNSAMPLE = 1
NETWORK_ENCODER_DOWNSAMPLE = 32
NETWORK_SHAPE = (
    math.ceil(DATA_SHAPE[0] / DATA_DOWNSAMPLE / NETWORK_ENCODER_DOWNSAMPLE) * NETWORK_ENCODER_DOWNSAMPLE,
    math.ceil(DATA_SHAPE[1] / DATA_DOWNSAMPLE / NETWORK_ENCODER_DOWNSAMPLE) * NETWORK_ENCODER_DOWNSAMPLE,
    1
)
DATA_PADDING = [(0, NETWORK_SHAPE[0] - DATA_SHAPE[0]),
                (0, NETWORK_SHAPE[1] - DATA_SHAPE[1]),
                (0, 0)]
DATA_FILE_LIMIT = 892
BATCH_SIZE = 5
base_dir = '/home/ryselis/toshiba_4tb/DataForMLTraining'
